### ISSUE TITLE
error with ‘Solver (ipopt) did not exit normally’

### ISSUE THREAD

**Issue by szyvcdc** [chaveza9/CAV-Game#4]
Dear Andres S. Chavez Armijos，

When running the code, I met the following error and tried to solve it, but nothing worked.

'''pyomo.common.errors.ApplicationError: Solver (ipopt) did not exit normally'''

May I have your help？

**Comment by chaveza9** [comment]
Sorry, this repository is not meant to be used yet. I am working on the release of this code, but it is related to this paper https://arxiv.org/abs/2303.16948 

If you have any questions please feel free to reach out directly. Otherwise, a related code is the following 

https://github.com/chaveza9/LaneChange-OCBF

**Comment by szyvcdc** [comment]
Thank you so much for your work.
